=== iKadmium/kadmium-dmx/kadmium-osc-dmx-dotnet-core/data/fixtures/fixture.schema.json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "title": "Fixture Definition",
  "type": "object",
  "properties": {
    "name": {
      "description": "The name of the fixture. This should be the same as the filename (without .json)",
      "type": "string"
    },
    "type": {
      "description": "The type of light the effect contains",
      "type": "string",
      "enum": [ "LED", "Effect", "Tungsten" ]
    },
    "channels": {
      "description": "The DMX channels the fixture uses",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the DMX Channel",
            "type": "string"
          },
          "dmx": {
            "description": "The address of the DMX Channel, starting at 1",
            "type": "integer"
          },
          "min": {
            "description": "The minimum value that should be used",
            "type": "integer",
            "default": 0
          },
          "max": {
            "description": "The maximum value that should be used",
            "type": "integer",
            "default": 255
          }
        },
        "required": [ "name", "dmx", "min", "max" ]
      }
    },
    "movements": {
      "description": "The movement axis the fixture uses",
      "type": "array",
      "items": {
        "type": "object",
        "properties": {
          "name": {
            "description": "The name of the axis",
            "type": "string"
          }
        }
      }
    }
  },
  "required": ["name", "type", "channels", "movements"]
}

=== iKadmium/kadmium-dmx/kadmium-osc-dmx-dotnet-core/data/fixtures/Chinese Moving Wash.json
{
  "$schema": "fixture.schema.json",
  "name": "Chinese Moving Wash",
  "type": "LED",
  "channels": [
    {
      "name": "Red",
      "dmx": 1,
      "min": 0,
      "max": 255
    },
    {
      "name": "Green",
      "dmx": 2,
      "min": 0,
      "max": 255
    },
    {
      "name": "Blue",
      "dmx": 3,
      "min": 0,
      "max": 255
    },
    {
      "name": "Strobe",
      "dmx": 4,
      "min": 0,
      "max": 255
    },
    {
      "name": "Apeshit",
      "dmx": 5,
      "min": 0,
      "max": 255
    },
    {
      "name": "Chase",
      "dmx": 6,
      "min": 0,
      "max": 255
    },
    {
      "name": "Program",
      "dmx": 7,
      "min": 0,
      "max": 255
    }
  ],
  "movements": [
    {
      "name": "Pan",
      "min": -270,
      "max": 270
    },
    {
      "name": "Tilt",
      "min": -135,
      "max": 135
    }
  ]
}

=== iKadmium/kadmium-dmx/data/fixtures/New Globe Moving Head.json
{
  "name": "New Globe Moving Head",
  "type": "LED",
  "channels": [
    {
      "name": "Master",
      "dmx": 1,
      "min": 255,
      "max": 0
    },
    {
      "name": "Strobe",
      "dmx": 2,
      "min": 255,
      "max": 0
    },
    {
      "name": "Color Macro",
      "dmx": 3,
      "min": 0,
      "max": 255
    },
    {
      "name": "No Idea",
      "dmx": 4,
      "min": 0,
      "max": 255
    },
    {
      "name": "Pan",
      "dmx": 5,
      "min": 0,
      "max": 255
    },
    {
      "name": "Tilt",
      "dmx": 6,
      "min": 0,
      "max": 255
    },
    {
      "name": "Red",
      "dmx": 7,
      "min": 255,
      "max": 0
    },
    {
      "name": "Green",
      "dmx": 8,
      "min": 255,
      "max": 0
    },
    {
      "name": "Blue",
      "dmx": 9,
      "min": 255,
      "max": 0
    }
  ],
  "movements": [
    {
      "name": "Pan",
      "min": -270,
      "max": 270
    },
    {
      "name": "Tilt",
      "min": -135,
      "max": 135
    }
  ]
}

=== iKadmium/kadmium-dmx/data/fixtures/Martin Mac 101.json
{
  "name": "Martin Mac 101",
  "type": "LED",
  "channels": [
    {
      "name": "Strobe",
      "dmx": 1,
      "min": 85,
      "max": 70
    },
    {
      "name": "Master",
      "dmx": 2,
      "min": 0,
      "max": 255
    },
    {
      "name": "PanCoarse",
      "dmx": 3,
      "min": 0,
      "max": 255
    },
    {
      "name": "PanFine",
      "dmx": 4,
      "min": 0,
      "max": 255
    },
    {
      "name": "TiltCoarse",
      "dmx": 5,
      "min": 0,
      "max": 255
    },
    {
      "name": "TiltFine",
      "dmx": 6,
      "min": 0,
      "max": 255
    },
    {
      "name": "FixtureControls",
      "dmx": 7,
      "min": 0,
      "max": 255
    },
    {
      "name": "ColorWheel",
      "dmx": 8,
      "min": 0,
      "max": 255
    },
    {
      "name": "Red",
      "dmx": 9,
      "min": 0,
      "max": 255
    },
    {
      "name": "Green",
      "dmx": 10,
      "min": 0,
      "max": 255
    },
    {
      "name": "Blue",
      "dmx": 11,
      "min": 0,
      "max": 255
    },
    {
      "name": "Color Temperature",
      "dmx": 12,
      "min": 0,
      "max": 255
    }
  ],
  "movements": [
    {
      "name": "Pan",
      "min": -270,
      "max": 270
    },
    {
      "name": "Tilt",
      "min": -120,
      "max": 120
    }
  ]
}
