=== iKadmium/kadmium-dmx/kadmium-osc-dmx-dotnet-core/data/fixtures/fixture.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema 
  xmlns:xsd="http://www.w3.org/2001/XMLSchema"
  xmlns="fixture"
  targetNamespace="fixture"
  elementFormDefault="qualified">

    <xsd:complexType name="fixtureDefinition">
        <xsd:sequence>
            <xsd:element name="channel" type="channel" minOccurs="0"
                         maxOccurs="unbounded">
            </xsd:element>
            <xsd:element name="movement" type="movement" minOccurs="0"
                         maxOccurs="unbounded">
            </xsd:element>
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string"/>
        <xsd:attribute name="type" type="xsd:string"/>
    </xsd:complexType>

    <xsd:complexType name="channel">
        <xsd:attribute name="name" type="xsd:string" use="required"/>
        <xsd:attribute name="dmx" type="xsd:int" use="required"/>
        <xsd:attribute name="min" type="xsd:int" default="0"/>
        <xsd:attribute name="max" type="xsd:int" default="255"/>
    </xsd:complexType>

    <xsd:complexType name="movement">
        <xsd:attribute name="type" type="xsd:string"/>
        <xsd:attribute name="min" type="xsd:int"/>
        <xsd:attribute name="max" type="xsd:int"/>
    </xsd:complexType>

    <xsd:element name="fixture" type="fixtureDefinition"/>

</xsd:schema>

=== iKadmium/kadmium-dmx/data/fixtures/Chinese RGBW 7ch.xml
<?xml version="1.0" encoding="UTF-8"?>
<fixture xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fixture.xsd"
         id="Chinese Moving Spot" type="LED">
    <channel name="PanCoarse" dmx="1" />
    <channel name="PanFine" dmx="2" />
    <channel name="TiltCoarse" dmx="3" />
    <channel name="TiltFine" dmx="4" />
    <channel name="MoveSpeed" dmx="5" />
    <channel name="Strobe" dmx="6" min="134" max="224" />
    <channel name="Master" dmx="6" min="225" />
    <channel name="Red" dmx="7" />
    <channel name="Green" dmx="8" />
    <channel name="Blue" dmx="9" />
    <channel name="Color Macros" dmx="10" />
    <channel name="ColorSpeed" dmx="11" />
    <channel name="Movement Macros" dmx="12" />
    <channel name="Gobo" dmx="13" />
    
    <movement type="Pan" min="-270" max="270"/>
    <movement type="Tilt" min="-135" max="135"/>
</fixture>

=== iKadmium/kadmium-dmx/data/fixtures/Magic 3D Easy View Moving Head RGBWAUV.xml
<?xml version="1.0" encoding="UTF-8"?>
<fixture xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fixture.xsd"
         id="Magic 3D Easy View Moving Head RGBWAUV" type="LED">
    <channel name="Master" dmx="1"/>
    <channel name="Red" dmx="2"/>
    <channel name="Green" dmx="3"/>
    <channel name="Blue" dmx="4"/>
    <channel name="White" dmx="5"/>
    <channel name="trueUV" dmx="6"/>
    <channel name="Amber" dmx="7"/>
    <channel name="Master" dmx="8" />
    <channel name="PanCoarse" dmx="9"/>
    <channel name="TiltCoarse" dmx="10"/>
    <channel name="PanFine" dmx="11"/>
    <channel name="TiltFine" dmx="12"/>
    <channel name="Speed" dmx="13"/>
    <channel name="Zoom" dmx="14" min="255"/>
    <channel name="Strobe" dmx="15" max="150"/>
    <channel name="Macro" dmx="16"/>
    <channel name="Speed Auto" dmx="17"/>
    <channel name="Reset" dmx="18"/>

    <movement type="Pan" min="-270" max="270" />
    <movement type="Tilt" min="-135" max="135" />
</fixture>

=== iKadmium/kadmium-dmx/data/fixtures/Chauvet Intimidator Spot 350 (14ch).xml
<?xml version="1.0" encoding="utf-8"?>
<fixture id="Chauvet Intimidator Spot 350 (8ch)" type="LED" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fixture.xsd">
  <channel name="Pan" dmx="1" min="0" max="255" />
    <channel name="PanFine" dmx="2" min="0" max="255" />
  <channel name="Tilt" dmx="3" min="0" max="255" />
    <channel name="TiltFine" dmx="4" min="0" max="255" />
    <channel name="Speed" dmx="5" min="0" max="255" />
  <channel name="Color Wheel" dmx="6" min="0" max="255" />
  <channel name="Gobo Wheel" dmx="7" min="0" max="255" />
  <channel name="Gobo Rotation" dmx="8" min="0" max="255" />
  <channel name="Prism" dmx="9" min="0" max="255" />
  <channel name="Focus" dmx="10" min="0" max="255" />
  <channel name="Master" dmx="11" min="0" max="7" />
  <channel name="Strobe" dmx="12" min="8" max="76" />
    <channel name="Control" dmx="13" min="0" max="255" />
    <channel name="Movement" dmx="14" min="0" max="255" />
  <movement type="Pan" min="-270" max="270" />
  <movement type="Tilt" min="-135" max="135" />
</fixture>

=== iKadmium/kadmium-dmx/kadmium-osc-dmx-dotnet-core/data/fixtures/Chinese RGBW 7ch.xml
<?xml version="1.0" encoding="UTF-8"?>
<fixture
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="fixture"
  xsi:schemaLocation="fixture fixture.xsd"
  xmlns:solver="solver"
  id="Chinese RGBW (7ch)" type="LED">
  <channel name="Master" dmx="1" />
  <channel name="Red" dmx="2" />
  <channel name="Green" dmx="3" />
  <channel name="Blue" dmx="4" />
  <channel name="White" dmx="5" />
  <channel name="Strobe" dmx="6" />
  <channel name="ColorMacros" dmx="7" />
</fixture>

=== iKadmium/kadmium-dmx/kadmium-osc-dmx-dotnet-core/data/fixtures/Chinese Moving Wash.xml
<?xml version="1.0" encoding="UTF-8"?>
<fixture
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="fixture"
  xsi:schemaLocation="fixture fixture.xsd"
  xmlns:solver="solver"
  id="Chinese Moving Wash" type="LED">
  
  <channel name="PanCoarse" dmx="1"/>
  <channel name="PanFine" dmx="2"/>
  <channel name="TiltCoarse" dmx="3"/>
  <channel name="TiltFine" dmx="4"/>
  <channel name="MotorSpeed" dmx="5"/>
  <channel name="Master" dmx="6"/>
  <channel name="Strobe" dmx="7"/>
  <channel name="ColorMacro" dmx="8"/>
  <channel name="MacroSpeed" dmx="9"/>
  <channel name="Red" dmx="10"/>
  <channel name="Green" dmx="11"/>
  <channel name="Blue" dmx="12"/>
  <channel name="White" dmx="13"/>

  <movement type="Pan" min="-270" max="270" />
  <movement type="Tilt" min="-135" max="135" />
</fixture>

=== iKadmium/kadmium-dmx/kadmium-osc-dmx-dotnet-core/data/fixtures/FadeCandy (program mode).xml
<?xml version="1.0" encoding="utf-8"?>
<fixture
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xmlns="fixture"
  xsi:schemaLocation="fixture fixture.xsd"
  xmlns:solver="solver"
  id="FadeCandy (program mode)" type="LED">

  <channel name="Red" dmx="1" min="0" max="255"/>
  <channel name="Green" dmx="2" min="0" max="255"/>
  <channel name="Blue" dmx="3" min="0" max="255"/>
  <channel name="Strobe" dmx="4" min="0" max="255"/>
  <channel name="Apeshit" dmx="5" min="0" max="255"/>
  <channel name="Chase" dmx="6" min="0" max="255"/>
  <channel name="Program" dmx="7" min="0" max="255"/>
</fixture>

=== iKadmium/kadmium-dmx/data/fixtures/Magic 3D Easy View Moving Head LED Beam.xml
<?xml version="1.0" encoding="UTF-8"?>
<fixture xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="fixture.xsd"
         id="Magic 3D Easy View Moving Head LED Beam" type="LED">
    <channel name="PanCoarse" dmx="1"/>
    <channel name="TiltCoarse" dmx="2"/>
    <channel name="Master" dmx="3"/>
    <channel name="Red" dmx="4"/>
    <channel name="Green" dmx="5"/>
    <channel name="Blue" dmx="6"/>
    <channel name="White" dmx="7"/>
    <channel name="Strobe" dmx="8" max="150"/>
    <channel name="Speed" dmx="9"/>
    <channel name="Color Macros" dmx="10"/>
    <channel name="Macro Speed" dmx="11"/>
    <channel name="Effect" dmx="12"/>
    <channel name="Effect Speed" dmx="13"/>
    <channel name="PanFine" dmx="14"/>
    <channel name="TiltFine" dmx="15"/>
    <channel name="Rest" dmx="16"/>

    <movement type="Pan" min="-270" max="270"/>
    <movement type="Tilt" min="-135" max="135"/>
</fixture>
