=== iKadmium/kadmium-dmx/data/venues/venue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="../solver.xsd"/>
    <xsd:include schemaLocation="../groups.xsd"/>
    <xsd:include schemaLocation="../transmitters.xsd"/>
    <xsd:include schemaLocation="../normalisedFloat.xsd"/>

    <xsd:complexType name="fixtureGroups">
        <xsd:sequence>
            <xsd:element name="group" type="fixtureGroup" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="fixtureGroup">
        <xsd:sequence/>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

	<xsd:complexType name="fixture">
		<xsd:sequence>
            <xsd:element name="groups" type="fixtureGroups" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="solver" type="solver" minOccurs="0"
				maxOccurs="unbounded"/>
            <xsd:element name="lookAtSolver" type="lookAtSolver" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="type" type="xsd:string" use="required"/>
		<xsd:attribute name="startChannel" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:int">
					<xsd:minInclusive value="1"/>
					<xsd:maxInclusive value="512"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="fixtureSet">
        <xsd:attribute name="src" type="xsd:anyURI" use="required"/>
        <xsd:attribute name="universe" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="universeTransmitter">
        <xsd:sequence/>
        <xsd:attribute name="id" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="universeTransmitters">
        <xsd:sequence>
            <xsd:element name="transmitter" type="universeTransmitter" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="fixtures">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="fixture" type="fixture" />
            <xsd:element name="fixtureSet" type="fixtureSet"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="universe">
    	<xsd:sequence>
            <xsd:element name="transmitters" type="universeTransmitters" minOccurs="1" maxOccurs="1" />
            <xsd:element name="fixtures" type="fixtures" minOccurs="1" maxOccurs="1" />
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="universes">
        <xsd:sequence>
            <xsd:element name="universe" type="universe" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="venue">
    	<xsd:sequence>
            <xsd:element name="groups" type="groups"/>
            <xsd:element name="transmitters" type="transmitters"/>
    		<xsd:element name="universes" type="universes"/>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="venue" type="venue">
        <xsd:key name="validGroup">
            <xsd:selector xpath="./groups/group"/>
            <xsd:field xpath="@name"/>
        </xsd:key>
        <xsd:keyref name="validGroupReference" refer="validGroup">
            <xsd:selector xpath="./universe/fixture/groups/group"/>
            <xsd:field xpath="@name"/>
        </xsd:keyref>

        <xsd:key name="validTransmitter">
            <xsd:selector xpath="./transmitters/enttecTransmitter"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
        <xsd:keyref name="validTransmitterReference" refer="validTransmitter">
            <xsd:selector xpath="./universe"/>
            <xsd:field xpath="@transmitter"/>
        </xsd:keyref>
    </xsd:element>

</xsd:schema>

=== iKadmium/kadmium-dmx/data/venues/The New Globe - Main Room.xml
<?xml version="1.0" encoding="UTF-8"?>
<venue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="venue.xsd"
       xmlns:xi="http://www.w3.org/2001/XInclude">

    <xi:include href="../groups.xml"/>
    <xi:include href="../transmitters.xml"/>

    <universes>
        <universe name="Main Universe">
            <transmitters>
                <transmitter id="enttecTransmitter"/>
                <transmitter id="sacnTransmitter"/>
            </transmitters>
            <fixtures>
                <fixture type="New Globe RGB LED" startChannel="19">
                    <groups>
                        <group name="vocalist"/>
                    </groups>
                    <solver type="hsb" enabled="true"/>
                    <solver type="fakeStrobe" enabled="true" countdownFrames="2"/>
                </fixture>

                <fixtureSet src="ColorRails.xml"/>

                <fixture type="New Globe RGB LED Dimmed" startChannel="13">
                    <groups>
                        <group name="drummer"/>
                    </groups>
                    <solver type="hsb" enabled="true"/>
                    <solver type="fakeStrobe" enabled="true" countdownFrames="2"/>
                </fixture>

                <fixture type="New Globe RGB LED Dimmed" startChannel="16">
                    <groups>
                        <group name="rearSides"/>
                    </groups>
                    <solver type="hsb" enabled="true"/>
                    <solver type="fakeStrobe" enabled="true" countdownFrames="2"/>
                </fixture>

                <fixtureSet src="Drum FadeCandy.xml"/>
                <fixtureSet src="Guitar FadeCandy.xml"/>
            </fixtures>
        </universe>
    </universes>
</venue>

=== iKadmium/kadmium-dmx/data/venues/Moving Spots.xml
<?xml version="1.0" encoding="UTF-8"?>
<venue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="venue.xsd">
    <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="../groups.xml" />
    <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="../transmitters.xml" />
    <universes>
        <universe name="Main Universe">
            <transmitters>
                <transmitter id="enttecTransmitter" />
            </transmitters>
            <fixtures>
                <fixture startChannel="401" type="Chinese Moving Spot">
                    <groups>
                        <group name="vocalist" />
                    </groups>
                    <solver type="hsb" />
                    <solver type="masterAtFull" />
                    <solver type="pan16bit" adjustment="90" />
                    <solver type="tilt16bit" adjustment="0" />
                    <solver type="fakeUV" />
                </fixture>
                <fixture startChannel="414" type="Chinese Moving Spot">
                    <groups>
                        <group name="guitarist" />
                    </groups>
                    <solver type="hsb" />
                    <solver type="masterAtFull" />
                    <solver type="pan16bit" adjustment="0.6" />
                    <solver type="tilt16bit" adjustment="0.6" />
                    <solver type="fakeUV" />
                </fixture>
                <fixture startChannel="427" type="Chinese Moving Spot">
                    <groups>
                        <group name="bassist" />
                    </groups>
                    <solver type="hsb" />
                    <solver type="masterAtFull" />
                    <solver type="pan16bit" adjustment="0.6" />
                    <solver type="tilt16bit" adjustment="0.6" />
                    <solver type="fakeUV" />
                </fixture>
                <fixture startChannel="440" type="Chinese Moving Spot">
                    <groups>
                        <group name="drummer" />
                    </groups>
                    <solver type="hsb" />
                    <solver type="masterAtFull" />
                    <solver type="pan16bit" adjustment="0.6" />
                    <solver type="tilt16bit" adjustment="0.6" />
                    <solver type="fakeUV" />
                </fixture>
            </fixtures>
        </universe>
    </universes>
</venue>

=== iKadmium/kadmium-dmx/data/venues/Moving Washes.xml
<?xml version="1.0" encoding="UTF-8"?>
<venue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="venue.xsd">
    <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="../groups.xml" />
    <xi:include xmlns:xi="http://www.w3.org/2001/XInclude" href="../transmitters.xml" />
    <universes>
        <universe name="New Universe">
            <transmitters>
                <transmitter id="enttecTransmitter" />
            </transmitters>
            <fixtures>
                <fixture startChannel="301" type="Chinese Moving Wash">
                    <groups>
                        <group name="rearSides" />
                    </groups>
                    <solver type="hsb" />
                    <solver type="masterAtFull" />
                    <solver type="pan16bit" />
                    <solver type="tilt16bit" />
                    <solver type="fakeUV" />
                </fixture>
                <fixture startChannel="315" type="Chinese Moving Wash">
                    <groups>
                        <group name="rearSides" />
                    </groups>
                    <solver type="hsb" />
                    <solver type="masterAtFull" />
                    <solver type="pan16bit" />
                    <solver type="tilt16bit" />
                    <solver type="fakeUV" />
                </fixture>
                <fixture startChannel="329" type="Chinese Moving Wash">
                    <groups>
                        <group name="rearSides" />
                    </groups>
                    <solver type="hsb" />
                    <solver type="masterAtFull" />
                    <solver type="pan16bit" />
                    <solver type="tilt16bit" />
                    <solver type="fakeUV" />
                </fixture>
                <fixture startChannel="343" type="Chinese Moving Wash">
                    <groups>
                        <group name="rearSides" />
                    </groups>
                    <solver type="hsb" />
                    <solver type="masterAtFull" />
                    <solver type="pan16bit" />
                    <solver type="tilt16bit" />
                    <solver type="fakeUV" />
                </fixture>
            </fixtures>
        </universe>
    </universes>
</venue>
