=== iKadmium/kadmium-dmx/data/venues/venue.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema
    xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:include schemaLocation="../solver.xsd"/>
    <xsd:include schemaLocation="../groups.xsd"/>
    <xsd:include schemaLocation="../transmitters.xsd"/>
    <xsd:include schemaLocation="../normalisedFloat.xsd"/>

    <xsd:complexType name="fixtureGroups">
        <xsd:sequence>
            <xsd:element name="group" type="fixtureGroup" minOccurs="0" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="fixtureGroup">
        <xsd:sequence/>
        <xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

	<xsd:complexType name="fixture">
		<xsd:sequence>
            <xsd:element name="groups" type="fixtureGroups" minOccurs="1" maxOccurs="1"/>
			<xsd:element name="solver" type="solver" minOccurs="0"
				maxOccurs="unbounded"/>
            <xsd:element name="lookAtSolver" type="lookAtSolver" minOccurs="0" maxOccurs="1" />
		</xsd:sequence>
		<xsd:attribute name="type" type="xsd:string" use="required"/>
		<xsd:attribute name="startChannel" use="optional">
			<xsd:simpleType>
				<xsd:restriction base="xsd:int">
					<xsd:minInclusive value="1"/>
					<xsd:maxInclusive value="512"/>
				</xsd:restriction>
			</xsd:simpleType>
		</xsd:attribute>
    </xsd:complexType>

    <xsd:complexType name="fixtureSet">
        <xsd:attribute name="src" type="xsd:anyURI" use="required"/>
        <xsd:attribute name="universe" type="xsd:string" use="optional"/>
    </xsd:complexType>

    <xsd:complexType name="universeTransmitter">
        <xsd:sequence/>
        <xsd:attribute name="id" type="xsd:string" use="required" />
    </xsd:complexType>

    <xsd:complexType name="universeTransmitters">
        <xsd:sequence>
            <xsd:element name="transmitter" type="universeTransmitter" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="fixtures">
        <xsd:choice minOccurs="0" maxOccurs="unbounded">
            <xsd:element name="fixture" type="fixture" />
            <xsd:element name="fixtureSet" type="fixtureSet"/>
        </xsd:choice>
    </xsd:complexType>

    <xsd:complexType name="universe">
    	<xsd:sequence>
            <xsd:element name="transmitters" type="universeTransmitters" minOccurs="1" maxOccurs="1" />
            <xsd:element name="fixtures" type="fixtures" minOccurs="1" maxOccurs="1" />
    	</xsd:sequence>
    	<xsd:attribute name="name" type="xsd:string" use="required"/>
    </xsd:complexType>

    <xsd:complexType name="universes">
        <xsd:sequence>
            <xsd:element name="universe" type="universe" minOccurs="1" maxOccurs="unbounded"/>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:complexType name="venue">
    	<xsd:sequence>
            <xsd:element name="groups" type="groups"/>
            <xsd:element name="transmitters" type="transmitters"/>
    		<xsd:element name="universes" type="universes"/>
    	</xsd:sequence>
    </xsd:complexType>

    <xsd:element name="venue" type="venue">
        <xsd:key name="validGroup">
            <xsd:selector xpath="./groups/group"/>
            <xsd:field xpath="@name"/>
        </xsd:key>
        <xsd:keyref name="validGroupReference" refer="validGroup">
            <xsd:selector xpath="./universe/fixture/groups/group"/>
            <xsd:field xpath="@name"/>
        </xsd:keyref>

        <xsd:key name="validTransmitter">
            <xsd:selector xpath="./transmitters/enttecTransmitter"/>
            <xsd:field xpath="@id"/>
        </xsd:key>
        <xsd:keyref name="validTransmitterReference" refer="validTransmitter">
            <xsd:selector xpath="./universe"/>
            <xsd:field xpath="@transmitter"/>
        </xsd:keyref>
    </xsd:element>

</xsd:schema>

=== iKadmium/kadmium-dmx/data/venues/The New Globe - Cinema Room.xml
<?xml version="1.0" encoding="UTF-8"?>
<venue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="venue.xsd"
       xmlns:xi="http://www.w3.org/2001/XInclude">

    <xi:include href="../groups.xml" />
    <xi:include href="../transmitters.xml" />

    <universes>
        <universe name="Main Universe">
            <transmitters>
                <transmitter id="sacnTransmitter"/>
                <transmitter id="enttecTransmitter"/>
            </transmitters>
            <fixtures>
                <fixture type="New Globe RGB LED" startChannel="1">
                    <groups>
                        <group name="vocalist"/>
                    </groups>
                    <solvers>
                        <solver type="hsb" enabled="true"/>
                        <solver type="fakeStrobe" enabled="true" countdownFrames="2"/>
                    </solvers>
                </fixture>

                <fixtureSet src="ColorRails.xml"/>

                <fixture type="New Globe RGB LED" startChannel="4">
                    <groups>
                        <group name="rearSides"/>
                    </groups>
                    <solvers>
                        <solver type="hsb" enabled="true"/>
                        <solver type="fakeStrobe" enabled="true" countdownFrames="2"/>
                    </solvers>
                </fixture>
            </fixtures>
        </universe>
    </universes>
</venue>

=== iKadmium/kadmium-dmx/data/venues/ColorRails.xml
<?xml version="1.0" encoding="UTF-8"?>
<venue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="venue.xsd"
       xmlns:xi="http://www.w3.org/2001/XInclude">

    <xi:include href="../groups.xml" />
    <xi:include href="../transmitters.xml" />
    
    <universes>
        <universe name="Personal Universe">
            <transmitters>
                <transmitter id="enttecTransmitter"/>
            </transmitters>
            <fixtures>
                <fixture startChannel="401" type="Chauvet ColorRail Master (no strobe)">
                    <groups>
                        <group name="bassist"/>
                    </groups>
                    <solver type="masterAtFull"/>
                </fixture>
                <fixture startChannel="402" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="bassist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>
                <fixture startChannel="405" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="bassist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>

                <fixture startChannel="408" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="bassist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>

                <fixture startChannel="411" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="bassist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>

                <fixture startChannel="414" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="bassist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>

                <fixture startChannel="417" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="bassist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>

                <fixture startChannel="420" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="bassist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>

                <fixture startChannel="423" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="bassist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>

                <fixture startChannel="427" type="Chauvet ColorRail Master (no strobe)">
                    <groups>
                        <group name="guitarist"/>
                    </groups>
                    <solver type="masterAtFull"/>
                </fixture>
                <fixture startChannel="428" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="guitarist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>
                <fixture startChannel="431" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="guitarist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>
                <fixture startChannel="434" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="guitarist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>
                <fixture startChannel="437" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="guitarist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>
                <fixture startChannel="440" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="guitarist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>
                <fixture startChannel="443" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="guitarist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>
                <fixture startChannel="446" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="guitarist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>
                <fixture startChannel="449" type="Chauvet ColorRail Section">
                    <groups>
                        <group name="guitarist"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeStrobe" countdownFrames="2"/>
                    <solver type="fakeUV"/>
                </fixture>
            </fixtures>
        </universe>
    </universes>
</venue>

=== iKadmium/kadmium-dmx/data/venues/The New Globe - Main Room with Moving Heads.xml
<?xml version="1.0" encoding="UTF-8"?>
<venue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="venue.xsd"
       xmlns:xi="http://www.w3.org/2001/XInclude">

    <xi:include href="../groups.xml"/>
    <xi:include href="../transmitters.xml"/>

    <universes>
        <universe name="Main Universe">
            <transmitters>
                <transmitter id="enttecTransmitter"/>
                <transmitter id="sacnTransmitter"/>
            </transmitters>
            <fixtures>
                <fixtureSet src="Moving Spots.xml"/>
                <fixtureSet src="Moving Washes.xml"/>
                <fixtureSet src="Drum FadeCandy.xml"/>
                <fixtureSet src="Guitar FadeCandy.xml"/>
            </fixtures>
        </universe>
    </universes>
</venue>

=== iKadmium/kadmium-dmx/kadmium-osc-dmx-dotnet-core/data/venues/Rehearsal Room.xml
<?xml version="1.0" encoding="UTF-8"?>
<venue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="venue"
    xsi:schemaLocation="venue venue.xsd"
    xmlns:solver="solver">

  <universes>
    <universe name="Main Universe">
      <transmitters>
        <transmitter id="enttecTransmitter"/>
        <transmitter id="sacnTransmitter"/>
      </transmitters>
      <fixtures>
        <fixtureSet src="Chinese Still Washes.xml"/>
        <fixtureSet src="Chinese Moving Washes.xml"/>
        <fixtureSet src="Guitar FadeCandy.xml"/>
        <fixtureSet src="Drum FadeCandy.xml"/>
      </fixtures>
    </universe>
  </universes>
</venue>

=== iKadmium/kadmium-dmx/data/venues/Guitar FadeCandy.xml
<?xml version="1.0" encoding="UTF-8"?>
<venue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="venue.xsd"
       xmlns:xi="http://www.w3.org/2001/XInclude">

    <xi:include href="../groups.xml" />
    <xi:include href="../transmitters.xml" />

    <universes>
        <universe name="Personal Universe">
            <transmitters>
                <transmitter id="sacnTransmitter"/>
            </transmitters>
            <fixtures>
                <fixture type="FadeCandy (program mode)" startChannel="480">
                    <groups>
                        <group name="guitarLEDs"/>
                    </groups>
                    <solver type="hsb"/>
                    <solver type="fakeUV"/>
                </fixture>
            </fixtures>
        </universe>
    </universes>
</venue>

=== iKadmium/kadmium-dmx/data/venues/Rehearsal Room.xml
<?xml version="1.0" encoding="UTF-8"?>
<venue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="venue.xsd"
       xmlns:xi="http://www.w3.org/2001/XInclude">

    <xi:include href="../groups.xml" />
    <xi:include href="../transmitters.xml" />

    <universes>
        <universe name="Main Universe">
            <transmitters>
                <transmitter id="enttecTransmitter"/>
                <transmitter id="sacnTransmitter"/>
            </transmitters>
            <fixtures>
                <fixture type="Nerhor NE-112" startChannel="64">
                    <groups>
                        <group name="vocalist"/>
                    </groups>
                    <solver type="hsb" enabled="true"/>
                </fixture>

                <fixtureSet src="ColorRails.xml" universe="Personal Universe"/>

                <fixture type="Nerhor NE-112" startChannel="68">
                    <groups>
                        <group name="rearSides"/>
                    </groups>
                    <solver type="hsb" enabled="true"/>
                </fixture>
            </fixtures>
        </universe>

    </universes>

</venue>

=== iKadmium/kadmium-dmx/kadmium-osc-dmx-dotnet-core/data/venues/Unity Preview.xml
<?xml version="1.0" encoding="UTF-8"?>
<venue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns="venue"
    xsi:schemaLocation="venue venue.xsd"
    xmlns:solver="solver">

  <universes>
    <universe name="Main Universe">
      <transmitters>
        <transmitter id="unityTransmitter"/>
      </transmitters>
      <fixtures>
        <fixtureSet src="Unity Still Washes.xml"/>
        <fixtureSet src="Unity Moving Washes.xml"/>
        <fixture type="Generic RGB" startChannel="480">
          <groups>
            <group name="guitarLEDs"/>
          </groups>
          <solvers>
            <solver:hsbSolver/>
            <solver:fakeUVSolver/>
            <solver:fakeStrobeSolver/>
          </solvers>
        </fixture>
      </fixtures>
    </universe>
    <universe name="Pixel Universe">
      <transmitters>
        <transmitter id="sacnTransmitter"/>
      </transmitters>
      <fixtures>
        <fixtureSet src="Unity FadeCandy.xml"/>
      </fixtures>
    </universe>
  </universes>
</venue>

=== iKadmium/kadmium-dmx/data/venues/The Zoo.xml
<?xml version="1.0" encoding="UTF-8"?>
<venue xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:noNamespaceSchemaLocation="venue.xsd"
       xmlns:xi="http://www.w3.org/2001/XInclude">

    <xi:include href="../groups.xml" />
    <xi:include href="../transmitters.xml" />

    <universes>
        <universe name="Main Universe">
            <transmitters>
                <transmitter id="enttecTransmitter"/>
                <transmitter id="sacnTransmitter"/>
            </transmitters>
            <fixtures>
                <fixture startChannel="1" type="General BRWG Par">
                    <groups>
                        <group name="vocalist"/>
                    </groups>
                    <solver type="hsb" enabled="true"/>
                </fixture>

                <fixtureSet src="ColorRails.xml" />

                <fixture startChannel="21" type="General RGB Par">
                    <groups>
                        <group name="drummer"/>
                    </groups>
                    <solver type="hsb" enabled="true"/>
                    <solver type="masterAtFull" enabled="true"/>
                </fixture>

                <fixture startChannel="13" type="General RGBW Par">
                    <groups>
                        <group name="rearSides"/>
                    </groups>
                    <solver type="hsb" enabled="true"/>
                    <solver type="masterAtFull" enabled="true"/>
                </fixture>
            </fixtures>
        </universe>
    </universes>
</venue>
