=== iKadmium/kadmium-dmx/data/colorwheels.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema elementFormDefault="qualified"
            xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <xsd:complexType name="color">
        <xsd:attribute name="rgb" type="xsd:string" />
        <xsd:attribute name="min" type="xsd:int" />
        <xsd:attribute name="max" type="xsd:int" />
    </xsd:complexType>

    <xsd:complexType name="fixture">
        <xsd:sequence>
            <xsd:element name="color" type="color" minOccurs="0" maxOccurs="unbounded" />
        </xsd:sequence>
        <xsd:attribute name="id" type="xsd:string" />
    </xsd:complexType>

    <xsd:complexType name="colorwheels">
        <xsd:sequence>
            <xsd:element name="fixture" type="fixture" minOccurs="0"
                         maxOccurs="unbounded"></xsd:element>
        </xsd:sequence>
    </xsd:complexType>

    <xsd:element name="colorwheels" type="colorwheels">
        <xsd:unique name="FixtureIDKey">
            <xsd:selector xpath="fixture" />
            <xsd:field xpath="@id" />
        </xsd:unique>
    </xsd:element>
</xsd:schema>

=== iKadmium/kadmium-dmx/data/colorwheels.xml
<?xml version="1.0" encoding="UTF-8"?>
<colorwheels xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="colorwheels.xsd">
    <fixture id="Nerhor Moving Head">
        <color min="0" max="15" rgb="FF0000" />
        <color min="16" max="31" rgb="00FF00" />
        <color min="32" max="47" rgb="0000FF" />
        <color min="48" max="63" rgb="FFFF00" />
        <color min="64" max="79" rgb="00FFFF" />
        <color min="80" max="95" rgb="FF00FF" />
        <color min="96" max="112" rgb="FFFFFF" />
    </fixture>
</colorwheels>
